development:
  stripe_publishable_key: pk_test_SfsdbExmYxdspINdi19kzCBT
  stripe_secret_key: sk_test_8z0KSqzNO09ybh0wkGPfDXA0

production:
  stripe_publishable_key: <% ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <% ENV['STRIPE_SECRET_KEY'] %>
