#encoding: UTF-8
class CreateFeeds < ActiveRecord::Migration
 def self.up
    create_table :feeds do |t|
      t.string :feedtag
      t.string :feedtext
      t.string :locale
      t.attachment :feedicon
      t.integer :vote
      t.boolean :active,:default=>true 
      t.timestamps
    end
    
    self.load
  end
  
  def self.down
    drop_table :feeds
  end
  
  def self.load
    
    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'Wise',:locale=>'en')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'Stupid',:locale=>'en')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'Disgusting',:locale=>'en')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'Awesome',:locale=>'en')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'Boring',:locale=>'en')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'Great',:locale=>'en')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'Childish',:locale=>'en')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'Interesting',:locale=>'en')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'Die',:locale=>'en')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'Who cares?',:locale=>'en')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'Enlighten',:locale=>'en')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'Relaxing',:locale=>'en')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'Nice',:locale=>'en')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'Lovable',:locale=>'en')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'Smart',:locale=>'en')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'Amiss',:locale=>'en')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'Deep',:locale=>'en')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'Sweet',:locale=>'en')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'Puzzling',:locale=>'en')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'Frightening',:locale=>'en')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'Horrible',:locale=>'en')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'Energising',:locale=>'en')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'Movingly',:locale=>'en')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'Motivating',:locale=>'en')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'Romantic',:locale=>'en')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'Repulsive',:locale=>'en')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'Technical',:locale=>'en')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'Expert',:locale=>'en')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'Know it all',:locale=>'en')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'Miserable',:locale=>'en')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'Ridiculous',:locale=>'en')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'Laughing',:locale=>'en')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'Crazy',:locale=>'en')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'Stimulant',:locale=>'en')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'Sexy',:locale=>'en')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'Elegant',:locale=>'en')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'Saggio',:locale=>'it')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'Stupido',:locale=>'it')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'Disgustoso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'Maestoso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'Noioso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'Grandioso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'Da Bambini',:locale=>'it')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'Interessante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'Muori',:locale=>'it')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'Chi se ne frega',:locale=>'it')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'Illuminante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'Rilassante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'Bello',:locale=>'it')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'Adorabile',:locale=>'it')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'Intelligente',:locale=>'it')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'Fuori Luogo',:locale=>'it')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'Profondo',:locale=>'it')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'Tenero',:locale=>'it')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'Sconcertante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'Spaventoso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'Orribile',:locale=>'it')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'Energizzante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'Commuovente',:locale=>'it')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'Motivante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'Romantico',:locale=>'it')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'Repulsive',:locale=>'it')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'Tecnico',:locale=>'it')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'Esperto',:locale=>'it')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'Lo sanno tutti',:locale=>'it')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'Miserabile',:locale=>'it')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'Ridicolo',:locale=>'it')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'Spassoso',:locale=>'it')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'Pazzesco',:locale=>'it')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'Eccitante',:locale=>'it')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'Attraente',:locale=>'it')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'Elegante',:locale=>'it')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'Weise',:locale=>'de')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'Dumm',:locale=>'de')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'Ekelhaft',:locale=>'de')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'Genial',:locale=>'de')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'Langweilig',:locale=>'de')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'Groß',:locale=>'de')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'Kindisch',:locale=>'de')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'Interessant',:locale=>'de')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'Sterben',:locale=>'de')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'wen interessiert das?',:locale=>'de')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'Erleuchten',:locale=>'de')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'Entspannen',:locale=>'de')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'Schön',:locale=>'de')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'Liebenswert',:locale=>'de')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'Intelligent',:locale=>'de')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'Schlecht',:locale=>'de')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'Tief',:locale=>'de')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'Süß',:locale=>'de')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'Rätselhaft',:locale=>'de')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'Erschreckend',:locale=>'de')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'Schrecklich',:locale=>'de')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'Erregungs',:locale=>'de')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'Ergreifend',:locale=>'de')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'Motivierende',:locale=>'de')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'Romantiker',:locale=>'de')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'Abstoßend',:locale=>'de')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'Technisch',:locale=>'de')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'Experte',:locale=>'de')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'Wissen es alle',:locale=>'de')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'Elend',:locale=>'de')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'Lächerlich',:locale=>'de')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'Lachen',:locale=>'de')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'Verrückt',:locale=>'de')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'Stimulans',:locale=>'de')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'Sexy',:locale=>'de')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'Eelegant',:locale=>'de')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'Sabio',:locale=>'es')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'Estúpido',:locale=>'es')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'Repugnante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'Impresionante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'Aburrido',:locale=>'es')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'Gran',:locale=>'es')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'Infantil',:locale=>'es')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'Interesante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'Morir',:locale=>'es')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'Aquiénleimporta?',:locale=>'es')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'Iluminar',:locale=>'es')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'Relajante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'Agradable',:locale=>'es')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'Adorable',:locale=>'es')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'Inteligente',:locale=>'es')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'Mal',:locale=>'es')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'Orofunda',:locale=>'es')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'Dulce',:locale=>'es')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'Desconcertante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'Aterrador',:locale=>'es')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'Horribles',:locale=>'es')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'Energizante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'Conmovedoramente',:locale=>'es')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'Motivador',:locale=>'es')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'Romántico',:locale=>'es')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'Repulsiva',:locale=>'es')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'Técnica',:locale=>'es')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'Experto',:locale=>'es')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'Saberlotodo',:locale=>'es')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'Miserables',:locale=>'es')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'Ridículo',:locale=>'es')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'Riendo',:locale=>'es')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'Loco',:locale=>'es')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'Estimulante',:locale=>'es')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'Sexy',:locale=>'es')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'Elegante',:locale=>'es')
    
    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'sage',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'stupide',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'dégoûtant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'impressionnant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'ennuyeux',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'grand',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'puéril',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'intéressant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'mourir',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'ons enfout?',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'éclairer',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'détente',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'agréable',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'aimable',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'intelligent',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'mal',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'profond',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'doux',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'déroutante',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'effrayant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'horrible',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'énergisant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'émouvante',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'motivant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'romantique',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'répulsif',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'technique',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'expert',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'toutsavoir',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'misérable',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'ridicule',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'rire',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'fou',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'stimulant',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'sexy',:locale=>'fr')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'élégant',:locale=>'fr')
    
    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'wijs',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'dom',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'walgelijk',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'geweldig',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'saai',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'grote',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'kinderachtig',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'interessant',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'sterven',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'who cares?',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'verlichten',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'ontspannen',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'nice',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'beminnelijk',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'smart',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'mis',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'diepe',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'zoete',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'puzzelen',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'beangstigend',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'afschuwelijk',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'energizing',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'ontroerend',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'motiverende',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'romantische',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'weerzinwekkend',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'technische',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'expert',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'weet het allemaal',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'ellendig',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'belachelijk',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'lachen',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'crazy',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'stimulant',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'sexy',:locale=>'nl')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'elegant',:locale=>'nl')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'sábio',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'estúpido',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'nojento',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'incrível',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'chato',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'grande',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'infantil',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'interessante',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'morrer',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'quem se importa?',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'iluminar',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'relaxante',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'bom',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'adorável',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'inteligente',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'errado',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'profunda ',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'doce',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'intrigante ',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'assustadora',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'horrível ',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'energizante',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'comovente',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'motivador',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'romântico',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'repulsiva',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'técnico',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'especialista',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'sabe tudo',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'miserável',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'ridículo',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'rindo',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'louco',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'estimulante',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'sexy',:locale=>'pt')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'elegante',:locale=>'pt')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'vis',:locale=>'se')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'dum',:locale=>'se')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'motbjudande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'häftigt',:locale=>'se')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'tråkig',:locale=>'se')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'bra',:locale=>'se')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'barns',:locale=>'se')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'intressant',:locale=>'se')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'dö',:locale=>'se')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'vem bryr sig?',:locale=>'se')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'upplysa',:locale=>'se')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'avkopplande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'fin',:locale=>'se')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'intagande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'smarta',:locale=>'se')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'tok',:locale=>'se')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'djup',:locale=>'se')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'söt',:locale=>'se')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'förbryllande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'skrämmande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'hemsk',:locale=>'se')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'energigivande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'gripande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'motiverande',:locale=>'se')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'romantiska',:locale=>'se')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'frånstötande ',:locale=>'se')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'teknisk',:locale=>'se')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'experten',:locale=>'se')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'vet allt',:locale=>'se')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'eländiga',:locale=>'se')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'löjligt',:locale=>'se')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'skrattar',:locale=>'se')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'galen',:locale=>'se')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'stimulantia',:locale=>'se')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'sexig',:locale=>'se')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'elegant',:locale=>'se')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'мудрый',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'глупо',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'отвратительно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'удивительным',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'скучно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'большой',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'детски',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'интересно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'умереть',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'кого это волнует?',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'просветить',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'расслабляющая',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'хороший',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'привлекательный',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'умный',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'сгодится',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'глубоко',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'сладкий',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'недоумение',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'страшно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'ужасно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'Бодрящий',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'трогательно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'мотивирует',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'романтический',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'отталкивающим ',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'техническая',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'все знают',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'несчастным',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'eländiga',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'смешно',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'смеясь',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'с ума',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'стимулятор',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'сексуальная',:locale=>'ru')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'элегантный',:locale=>'ru')

    Feed.create(:feedtag=>'FEED_WISE',:feedtext=>'聰明',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_STUPID',:feedtext=>'愚蠢的',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_DISGUSTING',:feedtext=>'噁心',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_AWESOME',:feedtext=>'真棒',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_BORING',:feedtext=>'無聊',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_GREAT',:feedtext=>'大',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_CHILDISH',:feedtext=>'幼稚',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_INTERESTING',:feedtext=>'有趣',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_DIE',:feedtext=>'死亡',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_WHO_CARES',:feedtext=>'誰在乎？',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_ENLIGHTEN',:feedtext=>'啟迪',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_RELAXING',:feedtext=>'放鬆',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_NICE',:feedtext=>'不錯',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_LOVABLE',:feedtext=>'可愛',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_SMART',:feedtext=>'智能',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_AMISS',:feedtext=>'不對勁',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_DEEP',:feedtext=>'深',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_SWEET',:feedtext=>'甜',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_PUZZLING',:feedtext=>'令人費解',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_FRIGHTENING',:feedtext=>'可怕',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_HORRIBLE',:feedtext=>'太可怕了',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_ENERGISING',:feedtext=>'激勵',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_MOVINGLY',:feedtext=>'動人',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_MOTIVATING',:feedtext=>'激勵',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_ROMANTINC',:feedtext=>'浪漫',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_REPULSIVE',:feedtext=>'厭 ',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_TECHNICAL',:feedtext=>'技術',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_EXPERT',:feedtext=>'專家',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_KNOW_IT_ALL',:feedtext=>'知道這一切',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_MISERABLE',:feedtext=>'慘',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_RIDICULOUS',:feedtext=>'可笑',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_LAUGHING',:feedtext=>'笑',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_CRAZY',:feedtext=>'瘋狂',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_STIMULANT',:feedtext=>'興奮劑',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_SEXY',:feedtext=>'性感',:locale=>'cn')
    Feed.create(:feedtag=>'FEED_ELEGANT',:feedtext=>'優雅',:locale=>'cn')
   end

end
