class CreateCountries < ActiveRecord::Migration
  
  def self.up
    create_table :countries do |t|
     t.string :country_code
     t.string :country_name
    end
    add_index :countries, :country_code
    self.load
  end
  
  def self.down
    drop_table :countries
  end
  
  def self.load
    Country.create :country_code=>"AD",:country_name=>"Andorra"
    Country.create :country_code=>"AE",:country_name=>"United Arab Emirates"
    Country.create :country_code=>"AF",:country_name=>"Afghanistan"
    Country.create :country_code=>"AG",:country_name=>"Antigua and Barbuda"
    Country.create :country_code=>"AI",:country_name=>"Anguilla"
    Country.create :country_code=>"AL",:country_name=>"Albania"
    Country.create :country_code=>"AM",:country_name=>"Armenia"
    Country.create :country_code=>"AN",:country_name=>"Netherlands Antilles"
    Country.create :country_code=>"AO",:country_name=>"Angola"
    Country.create :country_code=>"AQ",:country_name=>"Antarctica"
    Country.create :country_code=>"AR",:country_name=>"Argentina"
    Country.create :country_code=>"AS",:country_name=>"American Samoa"
    Country.create :country_code=>"AT",:country_name=>"Austria"
    Country.create :country_code=>"AU",:country_name=>"Australia"
    Country.create :country_code=>"AW",:country_name=>"Aruba"
    Country.create :country_code=>"AX",:country_name=>"Aland Islands"
    Country.create :country_code=>"AZ",:country_name=>"Azerbaijan"
    Country.create :country_code=>"BA",:country_name=>"Bosnia and Herzegovina"
    Country.create :country_code=>"BB",:country_name=>"Barbados"
    Country.create :country_code=>"BD",:country_name=>"Bangladesh"
    Country.create :country_code=>"BE",:country_name=>"Belgium"
    Country.create :country_code=>"BF",:country_name=>"Burkina Faso"
    Country.create :country_code=>"BG",:country_name=>"Bulgaria"
    Country.create :country_code=>"BH",:country_name=>"Bahrain"
    Country.create :country_code=>"BI",:country_name=>"Burundi"
    Country.create :country_code=>"BJ",:country_name=>"Benin"
    Country.create :country_code=>"BL",:country_name=>"Saint Barthélemy"
    Country.create :country_code=>"BM",:country_name=>"Bermuda"
    Country.create :country_code=>"BN",:country_name=>"Brunei"
    Country.create :country_code=>"BO",:country_name=>"Bolivia"
    Country.create :country_code=>"BQ",:country_name=>"Bonaire, Saint Eustatius and Saba "
    Country.create :country_code=>"BR",:country_name=>"Brazil"
    Country.create :country_code=>"BS",:country_name=>"Bahamas"
    Country.create :country_code=>"BT",:country_name=>"Bhutan"
    Country.create :country_code=>"BV",:country_name=>"Bouvet Island"
    Country.create :country_code=>"BW",:country_name=>"Botswana"
    Country.create :country_code=>"BY",:country_name=>"Belarus"
    Country.create :country_code=>"BZ",:country_name=>"Belize"
    Country.create :country_code=>"CA",:country_name=>"Canada"
    Country.create :country_code=>"CC",:country_name=>"Cocos Islands"
    Country.create :country_code=>"CD",:country_name=>"Democratic Republic of the Congo"
    Country.create :country_code=>"CF",:country_name=>"Central African Republic"
    Country.create :country_code=>"CG",:country_name=>"Republic of the Congo"
    Country.create :country_code=>"CH",:country_name=>"Switzerland"
    Country.create :country_code=>"CI",:country_name=>"Ivory Coast"
    Country.create :country_code=>"CK",:country_name=>"Cook Islands"
    Country.create :country_code=>"CL",:country_name=>"Chile"
    Country.create :country_code=>"CM",:country_name=>"Cameroon"
    Country.create :country_code=>"CN",:country_name=>"China"
    Country.create :country_code=>"CO",:country_name=>"Colombia"
    Country.create :country_code=>"CR",:country_name=>"Costa Rica"
    Country.create :country_code=>"CS",:country_name=>"Serbia and Montenegro"
    Country.create :country_code=>"CU",:country_name=>"Cuba"
    Country.create :country_code=>"CV",:country_name=>"Cape Verde"
    Country.create :country_code=>"CW",:country_name=>"Curaçao"
    Country.create :country_code=>"CX",:country_name=>"Christmas Island"
    Country.create :country_code=>"CY",:country_name=>"Cyprus"
    Country.create :country_code=>"CZ",:country_name=>"Czech Republic"
    Country.create :country_code=>"DE",:country_name=>"Germany"
    Country.create :country_code=>"DJ",:country_name=>"Djibouti"
    Country.create :country_code=>"DK",:country_name=>"Denmark"
    Country.create :country_code=>"DM",:country_name=>"Dominica"
    Country.create :country_code=>"DO",:country_name=>"Dominican Republic"
    Country.create :country_code=>"DZ",:country_name=>"Algeria"
    Country.create :country_code=>"EC",:country_name=>"Ecuador"
    Country.create :country_code=>"EE",:country_name=>"Estonia"
    Country.create :country_code=>"EG",:country_name=>"Egypt"
    Country.create :country_code=>"EH",:country_name=>"Western Sahara"
    Country.create :country_code=>"ER",:country_name=>"Eritrea"
    Country.create :country_code=>"ES",:country_name=>"Spain"
    Country.create :country_code=>"ET",:country_name=>"Ethiopia"
    Country.create :country_code=>"FI",:country_name=>"Finland"
    Country.create :country_code=>"FJ",:country_name=>"Fiji"
    Country.create :country_code=>"FK",:country_name=>"Falkland Islands"
    Country.create :country_code=>"FM",:country_name=>"Micronesia"
    Country.create :country_code=>"FO",:country_name=>"Faroe Islands"
    Country.create :country_code=>"FR",:country_name=>"France"
    Country.create :country_code=>"GA",:country_name=>"Gabon"
    Country.create :country_code=>"GB",:country_name=>"United Kingdom"
    Country.create :country_code=>"GD",:country_name=>"Grenada"
    Country.create :country_code=>"GE",:country_name=>"Georgia"
    Country.create :country_code=>"GF",:country_name=>"French Guiana"
    Country.create :country_code=>"GG",:country_name=>"Guernsey"
    Country.create :country_code=>"GH",:country_name=>"Ghana"
    Country.create :country_code=>"GI",:country_name=>"Gibraltar"
    Country.create :country_code=>"GL",:country_name=>"Greenland"
    Country.create :country_code=>"GM",:country_name=>"Gambia"
    Country.create :country_code=>"GN",:country_name=>"Guinea"
    Country.create :country_code=>"GP",:country_name=>"Guadeloupe"
    Country.create :country_code=>"GQ",:country_name=>"Equatorial Guinea"
    Country.create :country_code=>"GR",:country_name=>"Greece"
    Country.create :country_code=>"GS",:country_name=>"South Georgia and the South Sandwich Islands"
    Country.create :country_code=>"GT",:country_name=>"Guatemala"
    Country.create :country_code=>"GU",:country_name=>"Guam"
    Country.create :country_code=>"GW",:country_name=>"Guinea-Bissau"
    Country.create :country_code=>"GY",:country_name=>"Guyana"
    Country.create :country_code=>"HK",:country_name=>"Hong Kong"
    Country.create :country_code=>"HM",:country_name=>"Heard Island and McDonald Islands"
    Country.create :country_code=>"HN",:country_name=>"Honduras"
    Country.create :country_code=>"HR",:country_name=>"Croatia"
    Country.create :country_code=>"HT",:country_name=>"Haiti"
    Country.create :country_code=>"HU",:country_name=>"Hungary"
    Country.create :country_code=>"ID",:country_name=>"Indonesia"
    Country.create :country_code=>"IE",:country_name=>"Ireland"
    Country.create :country_code=>"IL",:country_name=>"Israel"
    Country.create :country_code=>"IM",:country_name=>"Isle of Man"
    Country.create :country_code=>"IN",:country_name=>"India"
    Country.create :country_code=>"IO",:country_name=>"British Indian Ocean Territory"
    Country.create :country_code=>"IQ",:country_name=>"Iraq"
    Country.create :country_code=>"IR",:country_name=>"Iran"
    Country.create :country_code=>"IS",:country_name=>"Iceland"
    Country.create :country_code=>"IT",:country_name=>"Italy"
    Country.create :country_code=>"JE",:country_name=>"Jersey"
    Country.create :country_code=>"JM",:country_name=>"Jamaica"
    Country.create :country_code=>"JO",:country_name=>"Jordan"
    Country.create :country_code=>"JP",:country_name=>"Japan"
    Country.create :country_code=>"KE",:country_name=>"Kenya"
    Country.create :country_code=>"KG",:country_name=>"Kyrgyzstan"
    Country.create :country_code=>"KH",:country_name=>"Cambodia"
    Country.create :country_code=>"KI",:country_name=>"Kiribati"
    Country.create :country_code=>"KM",:country_name=>"Comoros"
    Country.create :country_code=>"KN",:country_name=>"Saint Kitts and Nevis"
    Country.create :country_code=>"KP",:country_name=>"North Korea"
    Country.create :country_code=>"KR",:country_name=>"South Korea"
    Country.create :country_code=>"KW",:country_name=>"Kuwait"
    Country.create :country_code=>"KY",:country_name=>"Cayman Islands"
    Country.create :country_code=>"KZ",:country_name=>"Kazakhstan"
    Country.create :country_code=>"LA",:country_name=>"Laos"
    Country.create :country_code=>"LB",:country_name=>"Lebanon"
    Country.create :country_code=>"LC",:country_name=>"Saint Lucia"
    Country.create :country_code=>"LI",:country_name=>"Liechtenstein"
    Country.create :country_code=>"LK",:country_name=>"Sri Lanka"
    Country.create :country_code=>"LR",:country_name=>"Liberia"
    Country.create :country_code=>"LS",:country_name=>"Lesotho"
    Country.create :country_code=>"LT",:country_name=>"Lithuania"
    Country.create :country_code=>"LU",:country_name=>"Luxembourg"
    Country.create :country_code=>"LV",:country_name=>"Latvia"
    Country.create :country_code=>"LY",:country_name=>"Libya"
    Country.create :country_code=>"MA",:country_name=>"Morocco"
    Country.create :country_code=>"MC",:country_name=>"Monaco"
    Country.create :country_code=>"MD",:country_name=>"Moldova"
    Country.create :country_code=>"ME",:country_name=>"Montenegro"
    Country.create :country_code=>"MF",:country_name=>"Saint Martin"
    Country.create :country_code=>"MG",:country_name=>"Madagascar"
    Country.create :country_code=>"MH",:country_name=>"Marshall Islands"
    Country.create :country_code=>"MK",:country_name=>"Macedonia"
    Country.create :country_code=>"ML",:country_name=>"Mali"
    Country.create :country_code=>"MM",:country_name=>"Myanmar"
    Country.create :country_code=>"MN",:country_name=>"Mongolia"
    Country.create :country_code=>"MO",:country_name=>"Macao"
    Country.create :country_code=>"MP",:country_name=>"Northern Mariana Islands"
    Country.create :country_code=>"MQ",:country_name=>"Martinique"
    Country.create :country_code=>"MR",:country_name=>"Mauritania"
    Country.create :country_code=>"MS",:country_name=>"Montserrat"
    Country.create :country_code=>"MT",:country_name=>"Malta"
    Country.create :country_code=>"MU",:country_name=>"Mauritius"
    Country.create :country_code=>"MV",:country_name=>"Maldives"
    Country.create :country_code=>"MW",:country_name=>"Malawi"
    Country.create :country_code=>"MX",:country_name=>"Mexico"
    Country.create :country_code=>"MY",:country_name=>"Malaysia"
    Country.create :country_code=>"MZ",:country_name=>"Mozambique"
    Country.create :country_code=>"NA",:country_name=>"Namibia"
    Country.create :country_code=>"NC",:country_name=>"New Caledonia"
    Country.create :country_code=>"NE",:country_name=>"Niger"
    Country.create :country_code=>"NF",:country_name=>"Norfolk Island"
    Country.create :country_code=>"NG",:country_name=>"Nigeria"
    Country.create :country_code=>"NI",:country_name=>"Nicaragua"
    Country.create :country_code=>"NL",:country_name=>"Netherlands"
    Country.create :country_code=>"NO",:country_name=>"Norway"
    Country.create :country_code=>"NP",:country_name=>"Nepal"
    Country.create :country_code=>"NR",:country_name=>"Nauru"
    Country.create :country_code=>"NU",:country_name=>"Niue"
    Country.create :country_code=>"NZ",:country_name=>"New Zealand"
    Country.create :country_code=>"OM",:country_name=>"Oman"
    Country.create :country_code=>"PA",:country_name=>"Panama"
    Country.create :country_code=>"PE",:country_name=>"Peru"
    Country.create :country_code=>"PF",:country_name=>"French Polynesia"
    Country.create :country_code=>"PG",:country_name=>"Papua New Guinea"
    Country.create :country_code=>"PH",:country_name=>"Philippines"
    Country.create :country_code=>"PK",:country_name=>"Pakistan"
    Country.create :country_code=>"PL",:country_name=>"Poland"
    Country.create :country_code=>"PM",:country_name=>"Saint Pierre and Miquelon"
    Country.create :country_code=>"PN",:country_name=>"Pitcairn"
    Country.create :country_code=>"PR",:country_name=>"Puerto Rico"
    Country.create :country_code=>"PS",:country_name=>"Palestinian Territory"
    Country.create :country_code=>"PT",:country_name=>"Portugal"
    Country.create :country_code=>"PW",:country_name=>"Palau"
    Country.create :country_code=>"PY",:country_name=>"Paraguay"
    Country.create :country_code=>"QA",:country_name=>"Qatar"
    Country.create :country_code=>"RE",:country_name=>"Reunion"
    Country.create :country_code=>"RO",:country_name=>"Romania"
    Country.create :country_code=>"RS",:country_name=>"Serbia"
    Country.create :country_code=>"RU",:country_name=>"Russia"
    Country.create :country_code=>"RW",:country_name=>"Rwanda"
    Country.create :country_code=>"SA",:country_name=>"Saudi Arabia"
    Country.create :country_code=>"SB",:country_name=>"Solomon Islands"
    Country.create :country_code=>"SC",:country_name=>"Seychelles"
    Country.create :country_code=>"SD",:country_name=>"Sudan"
    Country.create :country_code=>"SE",:country_name=>"Sweden"
    Country.create :country_code=>"SG",:country_name=>"Singapore"
    Country.create :country_code=>"SH",:country_name=>"Saint Helena"
    Country.create :country_code=>"SI",:country_name=>"Slovenia"
    Country.create :country_code=>"SJ",:country_name=>"Svalbard and Jan Mayen"
    Country.create :country_code=>"SK",:country_name=>"Slovakia"
    Country.create :country_code=>"SL",:country_name=>"Sierra Leone"
    Country.create :country_code=>"SM",:country_name=>"San Marino"
    Country.create :country_code=>"SN",:country_name=>"Senegal"
    Country.create :country_code=>"SO",:country_name=>"Somalia"
    Country.create :country_code=>"SR",:country_name=>"Suriname"
    Country.create :country_code=>"SS",:country_name=>"South Sudan"
    Country.create :country_code=>"ST",:country_name=>"Sao Tome and Principe"
    Country.create :country_code=>"SV",:country_name=>"El Salvador"
    Country.create :country_code=>"SX",:country_name=>"Sint Maarten"
    Country.create :country_code=>"SY",:country_name=>"Syria"
    Country.create :country_code=>"SZ",:country_name=>"Swaziland"
    Country.create :country_code=>"TC",:country_name=>"Turks and Caicos Islands"
    Country.create :country_code=>"TD",:country_name=>"Chad"
    Country.create :country_code=>"TF",:country_name=>"French Southern Territories"
    Country.create :country_code=>"TG",:country_name=>"Togo"
    Country.create :country_code=>"TH",:country_name=>"Thailand"
    Country.create :country_code=>"TJ",:country_name=>"Tajikistan"
    Country.create :country_code=>"TK",:country_name=>"Tokelau"
    Country.create :country_code=>"TL",:country_name=>"East Timor"
    Country.create :country_code=>"TM",:country_name=>"Turkmenistan"
    Country.create :country_code=>"TN",:country_name=>"Tunisia"
    Country.create :country_code=>"TO",:country_name=>"Tonga"
    Country.create :country_code=>"TR",:country_name=>"Turkey"
    Country.create :country_code=>"TT",:country_name=>"Trinidad and Tobago"
    Country.create :country_code=>"TV",:country_name=>"Tuvalu"
    Country.create :country_code=>"TW",:country_name=>"Taiwan"
    Country.create :country_code=>"TZ",:country_name=>"Tanzania"
    Country.create :country_code=>"UA",:country_name=>"Ukraine"
    Country.create :country_code=>"UG",:country_name=>"Uganda"
    Country.create :country_code=>"UM",:country_name=>"United States Minor Outlying Islands"
    Country.create :country_code=>"US",:country_name=>"United States"
    Country.create :country_code=>"UY",:country_name=>"Uruguay"
    Country.create :country_code=>"UZ",:country_name=>"Uzbekistan"
    Country.create :country_code=>"VA",:country_name=>"Vatican"
    Country.create :country_code=>"VC",:country_name=>"Saint Vincent and the Grenadines"
    Country.create :country_code=>"VE",:country_name=>"Venezuela"
    Country.create :country_code=>"VG",:country_name=>"British Virgin Islands"
    Country.create :country_code=>"VI",:country_name=>"U.S. Virgin Islands"
    Country.create :country_code=>"VN",:country_name=>"Vietnam"
    Country.create :country_code=>"VU",:country_name=>"Vanuatu"
    Country.create :country_code=>"WF",:country_name=>"Wallis and Futuna"
    Country.create :country_code=>"WS",:country_name=>"Samoa"
    Country.create :country_code=>"XK",:country_name=>"Kosovo"
    Country.create :country_code=>"YE",:country_name=>"Yemen"
    Country.create :country_code=>"YT",:country_name=>"Mayotte"
    Country.create :country_code=>"ZA",:country_name=>"South Africa"
    Country.create :country_code=>"ZM",:country_name=>"Zambia"
    Country.create :country_code=>"ZW",:country_name=>"Zimbabwe"

  end
  
end
